question_data = [
    {"question": "A slug's blood is green.", "correct_answer": "True"},
    {"question": "The loudest animal is the African Elephant.", "correct_answer": "False"},
    {"question": "Approximately one quarter of human bones are in the feet.", "correct_answer": "True"},
    {"question": "The total surface area of a human lungs is the size of a football pitch.", "correct_answer": "True"},
    {"question": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.", "correct_answer": "True"},
    {"question": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.", "correct_answer": "False"},
    {"question": "It is illegal to pee in the Ocean in Portugal.", "correct_answer": "True"},
    {"question": "You can lead a cow down stairs but not up stairs.", "correct_answer": "False"},
    {"question": "Google was originally called 'Backrub'.", "correct_answer": "True"},
    {"question": "Buzz Aldrin's mother's maiden name was 'Moon'.", "correct_answer": "True"},
    {"question": "No piece of square dry paper can be folded in half more than 7 times.", "correct_answer": "False"},
    {"question": "A few ounces of chocolate can to kill a small dog.", "correct_answer": "True"},
     {"category": "Entertainment: Television", "type": "boolean", "difficulty": "medium",
      "question": "AMC's The Walking Dead, Rick, Carl, Daryl, Morgan, Carol and Maggie were introduced to us in Season 1.",
      "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
      "question": "Hippopotomonstrosesquippedaliophobia is the irrational fear of long words.",
      "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "History", "type": "boolean", "difficulty": "medium",
      "question": "The M41 Walker Bulldog remains in service in some countries to this day.",
      "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Geography", "type": "boolean", "difficulty": "easy",
      "question": "There is a city called Rome in every continent on Earth.",
      "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
      "question": "A defibrillator is used to start up a heartbeat once a heart has stopped beating.",
      "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Books", "type": "boolean", "difficulty": "easy",
      "question": "The book 1984 was published in 1949.", "correct_answer": "True",
      "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
      "question": "There are 86400 seconds in a day.", "correct_answer": "True",
      "incorrect_answers": ["False"]},
    {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
      "question": "Shaquille O'Neal appeared in the 1997 film &quot;Space Jam&quot;.",
      "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Board Games", "type": "boolean", "difficulty": "easy",
      "question": "The card game &quot;Munchkin&quot; won the 2001 Origins Award for Best Traditional Card Game.",
      "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "History", "type": "boolean", "difficulty": "medium",
      "question": "If you grab the bladed end of a longsword in a specific way, you will not cut yourself.",
      "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
      "question": "Sitting for more than three hours a day can cut two years off a person&#039;s life expectancy.",
      "correct_answer": "True", "incorrect_answers": ["False"]},
     {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean",
      "difficulty": "medium",
      "question": "The anime Attack on Titan was directed by Tetsur\u014d Araki, the same person who directed the anime Highschool of the Dead.",
      "correct_answer": "True", "incorrect_answers": ["False"]},
     {"category": "Mythology", "type": "boolean", "difficulty": "easy",
      "question": "According to Greek Mythology, Atlas was an Olympian God.",
      "correct_answer": "False", "incorrect_answers": ["True"]},
     {"category": "History", "type": "boolean", "difficulty": "medium",
      "question": "The Hundred Years&#039; War was fought for more than a hundred years.",
      "correct_answer": "True", "incorrect_answers": ["False"]},
     {"category": "Animals", "type": "boolean", "difficulty": "easy",
      "question": "A caterpillar has more muscles than humans do.",
      "correct_answer": "True", "incorrect_answers": ["False"]},
     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
      "question": "In RuneScape, one must complete the &quot;Dragon Slayer&quot; quest before equipping Rune Platelegs.",
      "correct_answer": "False", "incorrect_answers": ["True"]},
     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "hard",
      "question": "All of these maps were in &quot;Tom Clancy&#039;s Rainbow Six Siege&quot; on its initial release: House, Clubhouse, Border, Consulate.",
      "correct_answer": "False", "incorrect_answers": ["True"]},
     {"category": "Politics", "type": "boolean", "difficulty": "medium",
      "question": "The State of Queensland, Australia voted NO to a referendum for daylight savings in 1992.",
      "correct_answer": "True", "incorrect_answers": ["False"]},
     {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean",
      "difficulty": "easy", "question": "Kiznaiver is an adaptation of a manga.",
      "correct_answer": "False", "incorrect_answers": ["True"]},
     {"category": "Entertainment: Television", "type": "boolean", "difficulty": "easy",
      "question": "In 'Star Trek', Klingons are aliens.",
      "correct_answer": "True", "incorrect_answers": ["False"]},
     {"category": "Entertainment: Television", "type": "boolean", "difficulty": "easy",
      "question": "In 'Doctor Who', the Doctor gets his TARDIS by stealing it.",
      "correct_answer": "True", "incorrect_answers": ["False"]},
     {"category": "History", "type": "boolean", "difficulty": "easy",
      "question": "The French Kingdom helped the United States gain their independence over Great Britain during the Revolutionary War.",
      "correct_answer": "True", "incorrect_answers": ["False"]},
     {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean",
      "difficulty": "hard",
      "question": "In the 'Kagerou Daze'; series, Shintaro Kisaragi is prominently shown with the color red.",
      "correct_answer": "True", "incorrect_answers": ["False"]},
     {"category": "Science & Nature", "type": "boolean", "difficulty": "easy",
      "question": "Not including false teeth; A human has two sets of teeth in their lifetime.",
      "correct_answer": "True", "incorrect_answers": ["False"]},
     {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
      "question": "A Facebook campaign placed Rage Against The Machine&#039;s &quot;Killing in the Name Of&quot; as the UK Christmas Number 1 in 2009.",
      "correct_answer": "True", "incorrect_answers": ["False"]},
     {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
      "question": "Metallica collaborated with Rowan Atkinson's Mr Bean on a 1992 comic relief single.",
      "correct_answer": "False", "incorrect_answers": ["True"]},
     {"category": "Entertainment: Television", "type": "boolean", "difficulty": "easy",
      "question": "The Simpsons family is named after creator Matt Groening's real family.",
      "correct_answer": "True", "incorrect_answers": ["False"]},
     {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
      "question": "Green Day&#039;s album &#039;American Idiot&#039; is considered a &quot;punk rock opera.&quot;",
      "correct_answer": "True", "incorrect_answers": ["False"]},
     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
      "question": "In Resident Evil, only Chris has access to the grenade launcher.",
      "correct_answer": "False", "incorrect_answers": ["True"]},
     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
      "question": "Resident Evil 7 is the first first-person Resident Evil game.",
      "correct_answer": "False", "incorrect_answers": ["True"]}
]
